import type { DesignTemplate } from '@/types';

export const ecommerceTemplate: DesignTemplate = {
  slug: 'ecommerce',
  title: 'E-Commerce Platform',
  description: 'Microservices architecture for online shopping with product catalog, shopping cart, order processing, and payment integration',
  nodes: [
    {
      id: 'cdn-1',
      type: 'archComponent',
      position: { x: 100, y: 50 },
      data: {
        componentType: 'cdn',
        label: 'CloudFront CDN',
        config: {},
      },
    },
    {
      id: 'lb-1',
      type: 'archComponent',
      position: { x: 100, y: 200 },
      data: {
        componentType: 'load_balancer',
        label: 'Application LB',
        config: {},
      },
    },
    {
      id: 'web-1',
      type: 'archComponent',
      position: { x: 0, y: 350 },
      data: {
        componentType: 'app_server',
        label: 'Web Server 1',
        config: {},
      },
    },
    {
      id: 'web-2',
      type: 'archComponent',
      position: { x: 200, y: 350 },
      data: {
        componentType: 'app_server',
        label: 'Web Server 2',
        config: {},
      },
    },
    {
      id: 'api-gw',
      type: 'archComponent',
      position: { x: 450, y: 200 },
      data: {
        componentType: 'api_gateway',
        label: 'API Gateway',
        config: {},
      },
    },
    {
      id: 'product-svc',
      type: 'archComponent',
      position: { x: 350, y: 350 },
      data: {
        componentType: 'app_server',
        label: 'Product Service',
        config: {},
      },
    },
    {
      id: 'cart-svc',
      type: 'archComponent',
      position: { x: 550, y: 350 },
      data: {
        componentType: 'app_server',
        label: 'Cart Service',
        config: {},
      },
    },
    {
      id: 'order-svc',
      type: 'archComponent',
      position: { x: 750, y: 350 },
      data: {
        componentType: 'app_server',
        label: 'Order Service',
        config: {},
      },
    },
    {
      id: 'payment-svc',
      type: 'archComponent',
      position: { x: 950, y: 350 },
      data: {
        componentType: 'app_server',
        label: 'Payment Service',
        config: {},
      },
    },
    {
      id: 'product-db',
      type: 'archComponent',
      position: { x: 350, y: 500 },
      data: {
        componentType: 'postgres',
        label: 'Product DB',
        config: {},
      },
    },
    {
      id: 'order-db',
      type: 'archComponent',
      position: { x: 750, y: 500 },
      data: {
        componentType: 'postgres',
        label: 'Order DB',
        config: {},
      },
    },
    {
      id: 'redis-cache',
      type: 'archComponent',
      position: { x: 550, y: 500 },
      data: {
        componentType: 'redis',
        label: 'Redis Cache',
        config: {},
      },
    },
    {
      id: 's3-images',
      type: 'archComponent',
      position: { x: 100, y: 500 },
      data: {
        componentType: 'object_storage',
        label: 'Product Images',
        config: {},
      },
    },
    {
      id: 'kafka-events',
      type: 'archComponent',
      position: { x: 950, y: 500 },
      data: {
        componentType: 'kafka',
        label: 'Event Stream',
        config: {},
      },
    },
    {
      id: 'payment-gateway',
      type: 'archComponent',
      position: { x: 1150, y: 350 },
      data: {
        componentType: 'external_api',
        label: 'Stripe API',
        config: {},
      },
    },
  ],
  edges: [
    {
      id: 'e1',
      source: 'cdn-1',
      target: 'lb-1',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e2',
      source: 'lb-1',
      target: 'web-1',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e3',
      source: 'lb-1',
      target: 'web-2',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e4',
      source: 'cdn-1',
      target: 's3-images',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e5',
      source: 'web-1',
      target: 'api-gw',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e6',
      source: 'web-2',
      target: 'api-gw',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e7',
      source: 'api-gw',
      target: 'product-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e8',
      source: 'api-gw',
      target: 'cart-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e9',
      source: 'api-gw',
      target: 'order-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e10',
      source: 'api-gw',
      target: 'payment-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e11',
      source: 'product-svc',
      target: 'product-db',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e12',
      source: 'cart-svc',
      target: 'redis-cache',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e13',
      source: 'order-svc',
      target: 'order-db',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e14',
      source: 'payment-svc',
      target: 'payment-gateway',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e15',
      source: 'order-svc',
      target: 'kafka-events',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e16',
      source: 'payment-svc',
      target: 'kafka-events',
      type: 'archEdge',
      data: {},
    },
  ],
};
