import type { DesignTemplate } from '@/types';

export const iotPipelineTemplate: DesignTemplate = {
  slug: 'iot-pipeline',
  title: 'IoT Data Pipeline',
  description: 'Real-time IoT data ingestion, validation, aggregation, anomaly detection, and alerting system',
  nodes: [
    {
      id: 'iot-devices',
      type: 'archComponent',
      position: { x: 50, y: 50 },
      data: {
        componentType: 'external_api',
        label: 'IoT Devices',
        config: {},
      },
    },
    {
      id: 'api-gw',
      type: 'archComponent',
      position: { x: 50, y: 200 },
      data: {
        componentType: 'api_gateway',
        label: 'IoT Gateway',
        config: {},
      },
    },
    {
      id: 'kafka-ingest',
      type: 'archComponent',
      position: { x: 50, y: 350 },
      data: {
        componentType: 'kafka',
        label: 'Ingest Stream',
        config: {},
      },
    },
    {
      id: 'validator-1',
      type: 'archComponent',
      position: { x: 300, y: 350 },
      data: {
        componentType: 'serverless',
        label: 'Validator Lambda 1',
        config: {},
      },
    },
    {
      id: 'validator-2',
      type: 'archComponent',
      position: { x: 300, y: 480 },
      data: {
        componentType: 'serverless',
        label: 'Validator Lambda 2',
        config: {},
      },
    },
    {
      id: 'kafka-validated',
      type: 'archComponent',
      position: { x: 550, y: 350 },
      data: {
        componentType: 'kafka',
        label: 'Validated Stream',
        config: {},
      },
    },
    {
      id: 'aggregator',
      type: 'archComponent',
      position: { x: 550, y: 500 },
      data: {
        componentType: 'worker',
        label: 'Aggregator Service',
        config: {},
      },
    },
    {
      id: 'anomaly-detector',
      type: 'archComponent',
      position: { x: 800, y: 350 },
      data: {
        componentType: 'worker',
        label: 'Anomaly Detector',
        config: {},
      },
    },
    {
      id: 's3-raw',
      type: 'archComponent',
      position: { x: 50, y: 500 },
      data: {
        componentType: 'object_storage',
        label: 'Raw Data Lake',
        config: {},
      },
    },
    {
      id: 's3-processed',
      type: 'archComponent',
      position: { x: 800, y: 500 },
      data: {
        componentType: 'object_storage',
        label: 'Processed Data',
        config: {},
      },
    },
    {
      id: 'postgres-timeseries',
      type: 'archComponent',
      position: { x: 1050, y: 350 },
      data: {
        componentType: 'postgres',
        label: 'TimescaleDB',
        config: {},
      },
    },
    {
      id: 'redis-realtime',
      type: 'archComponent',
      position: { x: 1050, y: 500 },
      data: {
        componentType: 'redis',
        label: 'Realtime Cache',
        config: {},
      },
    },
    {
      id: 'alert-svc',
      type: 'archComponent',
      position: { x: 1050, y: 650 },
      data: {
        componentType: 'app_server',
        label: 'Alert Service',
        config: {},
      },
    },
    {
      id: 'dashboard-api',
      type: 'archComponent',
      position: { x: 1300, y: 350 },
      data: {
        componentType: 'app_server',
        label: 'Dashboard API',
        config: {},
      },
    },
    {
      id: 'external-webhook',
      type: 'archComponent',
      position: { x: 1300, y: 650 },
      data: {
        componentType: 'external_api',
        label: 'Webhook Targets',
        config: {},
      },
    },
  ],
  edges: [
    {
      id: 'e1',
      source: 'iot-devices',
      target: 'api-gw',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e2',
      source: 'api-gw',
      target: 'kafka-ingest',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e3',
      source: 'kafka-ingest',
      target: 'validator-1',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e4',
      source: 'kafka-ingest',
      target: 'validator-2',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e5',
      source: 'kafka-ingest',
      target: 's3-raw',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e6',
      source: 'validator-1',
      target: 'kafka-validated',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e7',
      source: 'validator-2',
      target: 'kafka-validated',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e8',
      source: 'kafka-validated',
      target: 'aggregator',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e9',
      source: 'kafka-validated',
      target: 'anomaly-detector',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e10',
      source: 'aggregator',
      target: 's3-processed',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e11',
      source: 'anomaly-detector',
      target: 'postgres-timeseries',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e12',
      source: 'aggregator',
      target: 'redis-realtime',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e13',
      source: 'anomaly-detector',
      target: 'alert-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e14',
      source: 'postgres-timeseries',
      target: 'dashboard-api',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e15',
      source: 'redis-realtime',
      target: 'dashboard-api',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e16',
      source: 'alert-svc',
      target: 'external-webhook',
      type: 'archEdge',
      data: {},
    },
  ],
};
