import type { DesignTemplate } from '@/types';

export const realtimeChatTemplate: DesignTemplate = {
  slug: 'realtime-chat',
  title: 'Realtime Chat',
  description: 'Scalable chat system with WebSocket servers, pub/sub messaging, and presence tracking',
  nodes: [
    {
      id: 'lb-1',
      type: 'archComponent',
      position: { x: 100, y: 50 },
      data: {
        componentType: 'load_balancer',
        label: 'Load Balancer',
        config: {},
      },
    },
    {
      id: 'ws-1',
      type: 'archComponent',
      position: { x: 0, y: 200 },
      data: {
        componentType: 'websocket',
        label: 'WebSocket Server 1',
        config: {},
      },
    },
    {
      id: 'ws-2',
      type: 'archComponent',
      position: { x: 200, y: 200 },
      data: {
        componentType: 'websocket',
        label: 'WebSocket Server 2',
        config: {},
      },
    },
    {
      id: 'ws-3',
      type: 'archComponent',
      position: { x: 400, y: 200 },
      data: {
        componentType: 'websocket',
        label: 'WebSocket Server 3',
        config: {},
      },
    },
    {
      id: 'redis-pubsub',
      type: 'archComponent',
      position: { x: 200, y: 350 },
      data: {
        componentType: 'redis',
        label: 'Redis Pub/Sub',
        config: {},
      },
    },
    {
      id: 'api-gw',
      type: 'archComponent',
      position: { x: 650, y: 50 },
      data: {
        componentType: 'api_gateway',
        label: 'REST API Gateway',
        config: {},
      },
    },
    {
      id: 'auth-svc',
      type: 'archComponent',
      position: { x: 550, y: 200 },
      data: {
        componentType: 'app_server',
        label: 'Auth Service',
        config: {},
      },
    },
    {
      id: 'msg-svc',
      type: 'archComponent',
      position: { x: 750, y: 200 },
      data: {
        componentType: 'app_server',
        label: 'Message Service',
        config: {},
      },
    },
    {
      id: 'presence-svc',
      type: 'archComponent',
      position: { x: 950, y: 200 },
      data: {
        componentType: 'app_server',
        label: 'Presence Service',
        config: {},
      },
    },
    {
      id: 'postgres-msg',
      type: 'archComponent',
      position: { x: 750, y: 350 },
      data: {
        componentType: 'postgres',
        label: 'Message Store',
        config: {},
      },
    },
    {
      id: 'postgres-user',
      type: 'archComponent',
      position: { x: 550, y: 350 },
      data: {
        componentType: 'postgres',
        label: 'User DB',
        config: {},
      },
    },
    {
      id: 'redis-presence',
      type: 'archComponent',
      position: { x: 950, y: 350 },
      data: {
        componentType: 'redis',
        label: 'Presence Cache',
        config: {},
      },
    },
    {
      id: 's3-media',
      type: 'archComponent',
      position: { x: 1150, y: 200 },
      data: {
        componentType: 'object_storage',
        label: 'Media Storage',
        config: {},
      },
    },
  ],
  edges: [
    {
      id: 'e1',
      source: 'lb-1',
      target: 'ws-1',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e2',
      source: 'lb-1',
      target: 'ws-2',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e3',
      source: 'lb-1',
      target: 'ws-3',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e4',
      source: 'ws-1',
      target: 'redis-pubsub',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e5',
      source: 'ws-2',
      target: 'redis-pubsub',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e6',
      source: 'ws-3',
      target: 'redis-pubsub',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e7',
      source: 'api-gw',
      target: 'auth-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e8',
      source: 'api-gw',
      target: 'msg-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e9',
      source: 'api-gw',
      target: 'presence-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e10',
      source: 'auth-svc',
      target: 'postgres-user',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e11',
      source: 'msg-svc',
      target: 'postgres-msg',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e12',
      source: 'msg-svc',
      target: 's3-media',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e13',
      source: 'presence-svc',
      target: 'redis-presence',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e14',
      source: 'redis-pubsub',
      target: 'msg-svc',
      type: 'archEdge',
      data: {},
    },
  ],
};
