import type { DesignTemplate } from '@/types';

export const videoStreamingTemplate: DesignTemplate = {
  slug: 'video-streaming',
  title: 'Video Streaming Platform',
  description: 'Video upload, transcoding pipeline, CDN delivery, and analytics for a streaming service',
  nodes: [
    {
      id: 'cdn-1',
      type: 'archComponent',
      position: { x: 100, y: 50 },
      data: {
        componentType: 'cdn',
        label: 'Video CDN',
        config: {},
      },
    },
    {
      id: 'api-gw',
      type: 'archComponent',
      position: { x: 450, y: 50 },
      data: {
        componentType: 'api_gateway',
        label: 'API Gateway',
        config: {},
      },
    },
    {
      id: 'upload-svc',
      type: 'archComponent',
      position: { x: 350, y: 200 },
      data: {
        componentType: 'app_server',
        label: 'Upload Service',
        config: {},
      },
    },
    {
      id: 'metadata-svc',
      type: 'archComponent',
      position: { x: 550, y: 200 },
      data: {
        componentType: 'app_server',
        label: 'Metadata Service',
        config: {},
      },
    },
    {
      id: 'streaming-svc',
      type: 'archComponent',
      position: { x: 750, y: 200 },
      data: {
        componentType: 'app_server',
        label: 'Streaming Service',
        config: {},
      },
    },
    {
      id: 's3-raw',
      type: 'archComponent',
      position: { x: 200, y: 350 },
      data: {
        componentType: 'object_storage',
        label: 'Raw Video Storage',
        config: {},
      },
    },
    {
      id: 'transcode-worker-1',
      type: 'archComponent',
      position: { x: 0, y: 500 },
      data: {
        componentType: 'worker',
        label: 'Transcoder 1',
        config: {},
      },
    },
    {
      id: 'transcode-worker-2',
      type: 'archComponent',
      position: { x: 200, y: 500 },
      data: {
        componentType: 'worker',
        label: 'Transcoder 2',
        config: {},
      },
    },
    {
      id: 'transcode-worker-3',
      type: 'archComponent',
      position: { x: 400, y: 500 },
      data: {
        componentType: 'worker',
        label: 'Transcoder 3',
        config: {},
      },
    },
    {
      id: 's3-processed',
      type: 'archComponent',
      position: { x: 200, y: 650 },
      data: {
        componentType: 'object_storage',
        label: 'Processed Video',
        config: {},
      },
    },
    {
      id: 'postgres-meta',
      type: 'archComponent',
      position: { x: 550, y: 350 },
      data: {
        componentType: 'postgres',
        label: 'Metadata DB',
        config: {},
      },
    },
    {
      id: 'redis-cache',
      type: 'archComponent',
      position: { x: 750, y: 350 },
      data: {
        componentType: 'redis',
        label: 'Cache',
        config: {},
      },
    },
    {
      id: 'kafka-jobs',
      type: 'archComponent',
      position: { x: 200, y: 800 },
      data: {
        componentType: 'kafka',
        label: 'Job Queue',
        config: {},
      },
    },
    {
      id: 'analytics-worker',
      type: 'archComponent',
      position: { x: 950, y: 500 },
      data: {
        componentType: 'serverless',
        label: 'Analytics Lambda',
        config: {},
      },
    },
    {
      id: 'postgres-analytics',
      type: 'archComponent',
      position: { x: 950, y: 650 },
      data: {
        componentType: 'postgres',
        label: 'Analytics DB',
        config: {},
      },
    },
  ],
  edges: [
    {
      id: 'e1',
      source: 'cdn-1',
      target: 's3-processed',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e2',
      source: 'api-gw',
      target: 'upload-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e3',
      source: 'api-gw',
      target: 'metadata-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e4',
      source: 'api-gw',
      target: 'streaming-svc',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e5',
      source: 'upload-svc',
      target: 's3-raw',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e6',
      source: 's3-raw',
      target: 'transcode-worker-1',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e7',
      source: 's3-raw',
      target: 'transcode-worker-2',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e8',
      source: 's3-raw',
      target: 'transcode-worker-3',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e9',
      source: 'transcode-worker-1',
      target: 's3-processed',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e10',
      source: 'transcode-worker-2',
      target: 's3-processed',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e11',
      source: 'transcode-worker-3',
      target: 's3-processed',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e12',
      source: 'metadata-svc',
      target: 'postgres-meta',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e13',
      source: 'streaming-svc',
      target: 'redis-cache',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e14',
      source: 'streaming-svc',
      target: 's3-processed',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e15',
      source: 'upload-svc',
      target: 'kafka-jobs',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e16',
      source: 'kafka-jobs',
      target: 'transcode-worker-1',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e17',
      source: 'kafka-jobs',
      target: 'transcode-worker-2',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e18',
      source: 'kafka-jobs',
      target: 'transcode-worker-3',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e19',
      source: 's3-processed',
      target: 'analytics-worker',
      type: 'archEdge',
      data: {},
    },
    {
      id: 'e20',
      source: 'analytics-worker',
      target: 'postgres-analytics',
      type: 'archEdge',
      data: {},
    },
  ],
};
