// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,archspec:10, architecture:14, vars:26, true:34, false:36, null:38, group:52, cdn:58, waf:60, api_gateway:62, app_server:64, worker:66, postgres:68, cache:70, object_storage:72, event_stream:74, simulation:98}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")rOYQPOOO_QPOOOdQPO'#C_QOQPOOOiQPO'#CbOOQO,58y,58yOnQPO,58|OsQPO'#CfOOQO1G.h1G.hO!RQPO'#DWO!dQPO'#DVO!rQPO'#DUOOQO'#Cg'#CgOOQO'#D`'#D`O#TQPO,59QOOQO,59Q,59QO#cQPO'#ChO#hQPO'#D^O#mQPO,59cOOQO'#DX'#DXO$_QPO'#DdO$dQPO,59qO%RQPO'#DSOOQO,59p,59pOOQO-E7^-E7^OOQO1G.l1G.lO%ZQPO,59SOOQO,59x,59xO%cQPO1G.}O%hQPO1G.zOOQO'#Cx'#CxOOQO'#DW'#DWOOQO,5:O,5:OOOQO-E7b-E7bO%mQPO'#DTOOQO'#Dc'#DcO%rQPO,59nOOQO,59n,59nO%zQPO'#CjOOQO'#Da'#DaO&PQPO1G.nOOQO1G.n1G.nO#hQPO7+$iOnQPO7+$fO&XQPO,59oOOQO-E7a-E7aOOQO1G/Y1G/YO&XQPO,59UOOQO-E7_-E7_OOQO7+$Y7+$YOOQO<<HT<<HTOOQO<<HQ<<HQO&pQPO'#DkO&wQPO'#CsOOQO'#Cl'#ClOOQO1G/Z1G/ZOOQO1G.p1G.pOOQO,5:V,5:VO&|QPO,5:VO'UQPO,59_O&XQPO'#DbO'ZQPO1G/qOOQO1G/q1G/qOOQO1G.y1G.yOOQO,59|,59|OOQO-E7`-E7`OOQO7+%]7+%]",
  stateData: "'f~O!ZOSPOS~OTQO~OVSO~O![TO~O!]UO~OXVO~OSXOW_O]`O!RaO~OibO|zX}zX!OzX!PzX~O|cO}cO!OcO!PcO~OXfOSxXWxX]xX!RxX~OSXOWiO]`O!RaO~OXjO~OXfO~OjmOmnOnnOonOpnOqnOrnOsnOtnOunO~OSoO~O|cO}cO!OcO!PcOSyaWyaXya]ya!Rya~OSrOWuO~OSvOWyO~O!]zO~O!]{O~O_|O~OSrOW!OO~O_!PO~OSvOW!RO~Oa!WOb!WOc!WOd!UO!]!WO!^!WO!`!VO~Of!ZO~P&XOS!]O~Oe!^Of!`O~OW!aO~Oe!^Of!dO~O![S~",
  goto: "$l!`PPP!aPP!dPPP!g!m!qP!uP!yPPPPPP#V!qPP!q#]PPPPPPPPP#`#i!q#m#q#xPPPP!qP#|$S$Y$`$fPPPPPP#VRPORRPQWUR!T{T]V^T[V^TwjxQ!X|Q!Y!PQ![!UR!b!^X!W|!P!U!^RlbQgZQkaR!SzTsftTZV^SYV^RpdTdYeQ^VRh^QxjR!QxQ!_![R!c!_QtfR}tQeYRqe",
  nodeNames: "⚠ LineComment Document Header Identifier archspec Architecture architecture } { Body BodyItem VarsBlock vars VarDecl : Value true false null [ , ] VariableRef GroupDecl = group ComponentDecl ComponentType cdn waf api_gateway app_server worker postgres cache object_storage event_stream PropertyBlock Property Connection ConnectionChain ConnectionNode ConnectionOp -> <-> <- -- SimulationBlock simulation",
  maxTerm: 62,
  nodeProps: [
    ["openedBy", 8,"{"],
    ["closedBy", 9,"}"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 5,
  tokenData: "(p~RgXY!jYZ!j]^!jpq!jrs!{tu$i|}$t}!O$y!O!P%^!P!Q%l!Q![&Z![!]&f!^!_&k!_!`'O!c!}'T!}#O'f#P#Q'k#R#S'T#T#j'T#j#k'p#k#o'T#o#p(f#q#r(k~!oS!Z~XY!jYZ!j]^!jpq!j~#OVOr!{rs#es#O!{#O#P#j#P;'S!{;'S;=`$c<%lO!{~#jO!]~~#mRO;'S!{;'S;=`#v;=`O!{~#yWOr!{rs#es#O!{#O#P#j#P;'S!{;'S;=`$c;=`<%l!{<%lO!{~$fP;=`<%l!{~$lP#o#p$o~$tO!`~~$yOe~~$|Q}!O%S!`!a%X~%XO!P~~%^O|~~%aP!Q![%d~%iP!^~!Q![%d~%oP!P!Q%r~%wSP~OY%rZ;'S%r;'S;=`&T<%lO%r~&WP;=`<%l%r~&`Q!^~!O!P%^!Q![&Z~&kO_~~&nP}!O&q~&vP!O~!`!a&y~'OO}~~'TOi~~'YSS~!Q!['T!c!}'T#R#S'T#T#o'T~'kOd~~'pOf~~'uSS~!Q![(R!c!}'T#R#S'T#T#o'T~(YS![~S~!Q![(R!c!}'T#R#S'T#T#o'T~(kOX~~(pOW~",
  tokenizers: [0],
  topRules: {"Document":[0,2]},
  specialized: [{term: 4, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 295
})
