// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,archspec:8, architecture:12, vars:24, true:32, false:34, null:36, simulation:48, group:58, cdn:64, waf:66, api_gateway:68, app_server:70, worker:72, postgres:74, cache:76, object_storage:78, event_stream:80}
export const parser = LRParser.deserialize({
  version: 14,
  states: "*zOYQPOOO_QPOOOdQPO'#C_QOQPOOOiQPO'#CaOOQO,58y,58yOnQPO,58{OsQPO'#CeOOQO1G.g1G.gO!RQPO'#DXO!dQPO'#DWO!rQPO'#DVOOQO'#Cf'#CfOOQO'#D_'#D_O#TQPO,59POOQO,59P,59PO#cQPO'#CgO#hQPO'#CsO#mQPO,59fOOQO'#DY'#DYO$_QPO'#DcO$dQPO,59rO%RQPO'#CuOOQO,59q,59qOOQO-E7]-E7]OOQO1G.k1G.kO%ZQPO,59ROOQO,59_,59_OOQO'#Dm'#DmOOQO'#Dn'#DnOOQO'#Do'#DoOOQO'#Dp'#DpOOQO'#Dq'#DqOOQO'#Dr'#DrOOQO'#Ds'#DsOOQO'#Dt'#DtOOQO'#Du'#DuOOQO'#C{'#C{O%cQPO1G/QO%hQPO1G.}OOQO'#DX'#DXOOQO,59},59}OOQO-E7a-E7aO%mQPO'#CvOOQO'#Db'#DbO%rQPO,59aOOQO,59a,59aO%zQPO'#CiOOQO'#D`'#D`O&PQPO1G.mOOQO1G.m1G.mO#hQPO7+$lOnQPO7+$iO&XQPO,59bOOQO-E7`-E7`OOQO1G.{1G.{O&XQPO,59TOOQO-E7^-E7^OOQO7+$X7+$XOOQO<<HW<<HWOOQO<<HT<<HTO&pQPO'#DkO&wQPO'#CrOOQO'#Ck'#CkOOQO1G.|1G.|OOQO1G.o1G.oOOQO,5:V,5:VO&|QPO,5:VO'UQPO,59^O&XQPO'#DaO'ZQPO1G/qOOQO1G/q1G/qOOQO1G.x1G.xOOQO,59{,59{OOQO-E7_-E7_OOQO7+%]7+%]",
  stateData: "'f~O!YOSPOS~OSQO~OUSO~O![TO~O!]UO~OWVO~OV_O[`OhaO!ZXO~OlbO}{X!O{X!P{X!Q{X~O}cO!OcO!PcO!QcO~OWfOVyX[yXhyX!ZyX~OViO[`OhaO!ZXO~OWjO~OWfO~OmwOplOqmOrnOsoOtpOuqOvrOwsOxtO~O!ZxO~O}cO!OcO!PcO!QcOVzaWza[zahza!Zza~OV!OO!Z{O~OV!SO!Z!PO~O!]!TO~O!]!UO~O^!VO~OV!XO!Z{O~O^!YO~OV![O!Z!PO~O`!aOa!aOb!aOc!_O!]!aO!^!aO!`!`O~Oe!dO~P&XO!Z!fO~Od!gOe!iO~OV!jO~Od!gOe!mO~O![!Z~",
  goto: "$y!jPPP!kP!nPPP!q!w!{P#PP#TPPPPPP#a!{P#g#p!{PP!{#tPPPPPPPPP!{#w#{$SPPPP$W$^$d$j$pPPPPPPP#aP$v$v$v$v$v$v$v$v$vRPORRPQWUR!^!UT]V^T[V^T!Qj!RQ!b!VQ!c!YQ!e!_R!k!gX!a!V!Y!_!gQgZQkaR!]!TT|f}RvbTZV^SYV^RydTdYeQ^VRh^Q!RjR!Z!RQ!h!eR!l!hQ}fR!W}QeYRzeRub",
  nodeNames: "⚠ LineComment Document Header archspec Architecture architecture } { Body BodyItem VarsBlock vars VarDecl : Value true false null [ , ] VariableRef SimulationBlock simulation PropertyBlock Property GroupDecl = group ComponentDecl ComponentType cdn waf api_gateway app_server worker postgres cache object_storage event_stream Connection ConnectionChain ConnectionNode ConnectionOp -> <-> <- --",
  maxTerm: 71,
  nodeProps: [
    ["openedBy", 7,"{"],
    ["closedBy", 8,"}"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 5,
  tokenData: "(p~RgXY!jYZ!j]^!jpq!jrs!{tu$i|}$t}!O$y!O!P%^!P!Q%l!Q![&Z![!]&f!^!_&k!_!`'O!c!}'T!}#O'f#P#Q'k#R#S'T#T#j'T#j#k'p#k#o'T#o#p(f#q#r(k~!oS!Y~XY!jYZ!j]^!jpq!j~#OVOr!{rs#es#O!{#O#P#j#P;'S!{;'S;=`$c<%lO!{~#jO!]~~#mRO;'S!{;'S;=`#v;=`O!{~#yWOr!{rs#es#O!{#O#P#j#P;'S!{;'S;=`$c;=`<%l!{<%lO!{~$fP;=`<%l!{~$lP#o#p$o~$tO!`~~$yOd~~$|Q}!O%S!`!a%X~%XO!Q~~%^O}~~%aP!Q![%d~%iP!^~!Q![%d~%oP!P!Q%r~%wSP~OY%rZ;'S%r;'S;=`&T<%lO%r~&WP;=`<%l%r~&`Q!^~!O!P%^!Q![&Z~&kO^~~&nP}!O&q~&vP!P~!`!a&y~'OO!O~~'TOl~~'YS!Z~!Q!['T!c!}'T#R#S'T#T#o'T~'kOc~~'pOe~~'uS!Z~!Q![(R!c!}'T#R#S'T#T#o'T~(YS![~!Z~!Q![(R!c!}'T#R#S'T#T#o'T~(kOW~~(pOV~",
  tokenizers: [0],
  topRules: {"Document":[0,2]},
  dynamicPrecedences: {"63":1,"64":1,"65":1,"66":1,"67":1,"68":1,"69":1,"70":1,"71":1},
  specialized: [{term: 57, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 295
})
