/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalkthroughSlugRouteImport } from './routes/walkthrough.$slug'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as FolderFolderIdRouteImport } from './routes/folder.$folderId'
import { Route as DesignDesignIdRouteImport } from './routes/design.$designId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkthroughSlugRoute = WalkthroughSlugRouteImport.update({
  id: '/walkthrough/$slug',
  path: '/walkthrough/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderFolderIdRoute = FolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignDesignIdRoute = DesignDesignIdRouteImport.update({
  id: '/design/$designId',
  path: '/design/$designId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/design/$designId': typeof DesignDesignIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/walkthrough/$slug': typeof WalkthroughSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/design/$designId': typeof DesignDesignIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/walkthrough/$slug': typeof WalkthroughSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/design/$designId': typeof DesignDesignIdRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/walkthrough/$slug': typeof WalkthroughSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/design/$designId'
    | '/folder/$folderId'
    | '/share/$slug'
    | '/walkthrough/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/design/$designId'
    | '/folder/$folderId'
    | '/share/$slug'
    | '/walkthrough/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/design/$designId'
    | '/folder/$folderId'
    | '/share/$slug'
    | '/walkthrough/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DesignDesignIdRoute: typeof DesignDesignIdRoute
  FolderFolderIdRoute: typeof FolderFolderIdRoute
  ShareSlugRoute: typeof ShareSlugRoute
  WalkthroughSlugRoute: typeof WalkthroughSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walkthrough/$slug': {
      id: '/walkthrough/$slug'
      path: '/walkthrough/$slug'
      fullPath: '/walkthrough/$slug'
      preLoaderRoute: typeof WalkthroughSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$folderId': {
      id: '/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof FolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$designId': {
      id: '/design/$designId'
      path: '/design/$designId'
      fullPath: '/design/$designId'
      preLoaderRoute: typeof DesignDesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DesignDesignIdRoute: DesignDesignIdRoute,
  FolderFolderIdRoute: FolderFolderIdRoute,
  ShareSlugRoute: ShareSlugRoute,
  WalkthroughSlugRoute: WalkthroughSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
